<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Asia
            ['name' => 'Japan', 'code' => 'jp'],
            ['name' => 'South Korea', 'code' => 'kr'],
            ['name' => 'China', 'code' => 'cn'],
            ['name' => 'Taiwan', 'code' => 'tw'],
            ['name' => 'Hong Kong', 'code' => 'hk'],
            ['name' => 'Singapore', 'code' => 'sg'],
            ['name' => 'Thailand', 'code' => 'th'],
            ['name' => 'Vietnam', 'code' => 'vn'],
            ['name' => 'Cambodia', 'code' => 'kh'],
            ['name' => 'Laos', 'code' => 'la'],
            ['name' => 'Myanmar', 'code' => 'mm'],
            ['name' => 'Malaysia', 'code' => 'my'],
            ['name' => 'Indonesia', 'code' => 'id'],
            ['name' => 'Philippines', 'code' => 'ph'],
            ['name' => 'India', 'code' => 'in'],
            ['name' => 'Nepal', 'code' => 'np'],
            ['name' => 'Bhutan', 'code' => 'bt'],
            ['name' => 'Bangladesh', 'code' => 'bd'],
            ['name' => 'Sri Lanka', 'code' => 'lk'],
            ['name' => 'Maldives', 'code' => 'mv'],
            ['name' => 'Pakistan', 'code' => 'pk'],
            ['name' => 'Afghanistan', 'code' => 'af'],
            ['name' => 'Iran', 'code' => 'ir'],
            ['name' => 'Iraq', 'code' => 'iq'],
            ['name' => 'Kuwait', 'code' => 'kw'],
            ['name' => 'Saudi Arabia', 'code' => 'sa'],
            ['name' => 'Qatar', 'code' => 'qa'],
            ['name' => 'United Arab Emirates', 'code' => 'ae'],
            ['name' => 'Oman', 'code' => 'om'],
            ['name' => 'Yemen', 'code' => 'ye'],
            ['name' => 'Jordan', 'code' => 'jo'],
            ['name' => 'Lebanon', 'code' => 'lb'],
            ['name' => 'Syria', 'code' => 'sy'],
            ['name' => 'Israel', 'code' => 'il'],
            ['name' => 'Palestine', 'code' => 'ps'],
            ['name' => 'Cyprus', 'code' => 'cy'],
            ['name' => 'Turkey', 'code' => 'tr'],
            ['name' => 'Georgia', 'code' => 'ge'],
            ['name' => 'Armenia', 'code' => 'am'],
            ['name' => 'Azerbaijan', 'code' => 'az'],
            ['name' => 'Kazakhstan', 'code' => 'kz'],
            ['name' => 'Uzbekistan', 'code' => 'uz'],
            ['name' => 'Kyrgyzstan', 'code' => 'kg'],
            ['name' => 'Tajikistan', 'code' => 'tj'],
            ['name' => 'Turkmenistan', 'code' => 'tm'],
            ['name' => 'Mongolia', 'code' => 'mn'],
            ['name' => 'North Korea', 'code' => 'kp'],

            // Europe
            ['name' => 'United Kingdom', 'code' => 'gb'],
            ['name' => 'Ireland', 'code' => 'ie'],
            ['name' => 'France', 'code' => 'fr'],
            ['name' => 'Germany', 'code' => 'de'],
            ['name' => 'Italy', 'code' => 'it'],
            ['name' => 'Spain', 'code' => 'es'],
            ['name' => 'Portugal', 'code' => 'pt'],
            ['name' => 'Netherlands', 'code' => 'nl'],
            ['name' => 'Belgium', 'code' => 'be'],
            ['name' => 'Luxembourg', 'code' => 'lu'],
            ['name' => 'Switzerland', 'code' => 'ch'],
            ['name' => 'Austria', 'code' => 'at'],
            ['name' => 'Czech Republic', 'code' => 'cz'],
            ['name' => 'Slovakia', 'code' => 'sk'],
            ['name' => 'Poland', 'code' => 'pl'],
            ['name' => 'Hungary', 'code' => 'hu'],
            ['name' => 'Romania', 'code' => 'ro'],
            ['name' => 'Bulgaria', 'code' => 'bg'],
            ['name' => 'Greece', 'code' => 'gr'],
            ['name' => 'Albania', 'code' => 'al'],
            ['name' => 'North Macedonia', 'code' => 'mk'],
            ['name' => 'Serbia', 'code' => 'rs'],
            ['name' => 'Croatia', 'code' => 'hr'],
            ['name' => 'Slovenia', 'code' => 'si'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'ba'],
            ['name' => 'Montenegro', 'code' => 'me'],
            ['name' => 'Kosovo', 'code' => 'xk'],
            ['name' => 'Moldova', 'code' => 'md'],
            ['name' => 'Ukraine', 'code' => 'ua'],
            ['name' => 'Belarus', 'code' => 'by'],
            ['name' => 'Lithuania', 'code' => 'lt'],
            ['name' => 'Latvia', 'code' => 'lv'],
            ['name' => 'Estonia', 'code' => 'ee'],
            ['name' => 'Finland', 'code' => 'fi'],
            ['name' => 'Sweden', 'code' => 'se'],
            ['name' => 'Norway', 'code' => 'no'],
            ['name' => 'Denmark', 'code' => 'dk'],
            ['name' => 'Iceland', 'code' => 'is'],
            ['name' => 'Malta', 'code' => 'mt'],

            // North America
            ['name' => 'United States', 'code' => 'us'],
            ['name' => 'Canada', 'code' => 'ca'],
            ['name' => 'Mexico', 'code' => 'mx'],
            ['name' => 'Guatemala', 'code' => 'gt'],
            ['name' => 'Belize', 'code' => 'bz'],
            ['name' => 'El Salvador', 'code' => 'sv'],
            ['name' => 'Honduras', 'code' => 'hn'],
            ['name' => 'Nicaragua', 'code' => 'ni'],
            ['name' => 'Costa Rica', 'code' => 'cr'],
            ['name' => 'Panama', 'code' => 'pa'],
            ['name' => 'Cuba', 'code' => 'cu'],
            ['name' => 'Jamaica', 'code' => 'jm'],
            ['name' => 'Haiti', 'code' => 'ht'],
            ['name' => 'Dominican Republic', 'code' => 'do'],
            ['name' => 'Puerto Rico', 'code' => 'pr'],
            ['name' => 'Bahamas', 'code' => 'bs'],
            ['name' => 'Barbados', 'code' => 'bb'],
            ['name' => 'Trinidad and Tobago', 'code' => 'tt'],
            ['name' => 'Grenada', 'code' => 'gd'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'vc'],
            ['name' => 'Saint Lucia', 'code' => 'lc'],
            ['name' => 'Dominica', 'code' => 'dm'],
            ['name' => 'Antigua and Barbuda', 'code' => 'ag'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'kn'],

            // South America
            ['name' => 'Brazil', 'code' => 'br'],
            ['name' => 'Argentina', 'code' => 'ar'],
            ['name' => 'Chile', 'code' => 'cl'],
            ['name' => 'Peru', 'code' => 'pe'],
            ['name' => 'Colombia', 'code' => 'co'],
            ['name' => 'Venezuela', 'code' => 've'],
            ['name' => 'Ecuador', 'code' => 'ec'],
            ['name' => 'Bolivia', 'code' => 'bo'],
            ['name' => 'Paraguay', 'code' => 'py'],
            ['name' => 'Uruguay', 'code' => 'uy'],
            ['name' => 'Guyana', 'code' => 'gy'],
            ['name' => 'Suriname', 'code' => 'sr'],
            ['name' => 'French Guiana', 'code' => 'gf'],

            // Africa
            ['name' => 'South Africa', 'code' => 'za'],
            ['name' => 'Egypt', 'code' => 'eg'],
            ['name' => 'Morocco', 'code' => 'ma'],
            ['name' => 'Algeria', 'code' => 'dz'],
            ['name' => 'Tunisia', 'code' => 'tn'],
            ['name' => 'Libya', 'code' => 'ly'],
            ['name' => 'Sudan', 'code' => 'sd'],
            ['name' => 'South Sudan', 'code' => 'ss'],
            ['name' => 'Ethiopia', 'code' => 'et'],
            ['name' => 'Kenya', 'code' => 'ke'],
            ['name' => 'Tanzania', 'code' => 'tz'],
            ['name' => 'Uganda', 'code' => 'ug'],
            ['name' => 'Rwanda', 'code' => 'rw'],
            ['name' => 'Burundi', 'code' => 'bi'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'cd'],
            ['name' => 'Republic of the Congo', 'code' => 'cg'],
            ['name' => 'Central African Republic', 'code' => 'cf'],
            ['name' => 'Cameroon', 'code' => 'cm'],
            ['name' => 'Chad', 'code' => 'td'],
            ['name' => 'Niger', 'code' => 'ne'],
            ['name' => 'Nigeria', 'code' => 'ng'],
            ['name' => 'Ghana', 'code' => 'gh'],
            ['name' => 'Ivory Coast', 'code' => 'ci'],
            ['name' => 'Senegal', 'code' => 'sn'],
            ['name' => 'Mali', 'code' => 'ml'],
            ['name' => 'Burkina Faso', 'code' => 'bf'],
            ['name' => 'Guinea', 'code' => 'gn'],
            ['name' => 'Sierra Leone', 'code' => 'sl'],
            ['name' => 'Liberia', 'code' => 'lr'],
            ['name' => 'Togo', 'code' => 'tg'],
            ['name' => 'Benin', 'code' => 'bj'],
            ['name' => 'Gabon', 'code' => 'ga'],
            ['name' => 'Equatorial Guinea', 'code' => 'gq'],
            ['name' => 'Sao Tome and Principe', 'code' => 'st'],
            ['name' => 'Angola', 'code' => 'ao'],
            ['name' => 'Zambia', 'code' => 'zm'],
            ['name' => 'Zimbabwe', 'code' => 'zw'],
            ['name' => 'Botswana', 'code' => 'bw'],
            ['name' => 'Namibia', 'code' => 'na'],
            ['name' => 'Lesotho', 'code' => 'ls'],
            ['name' => 'Eswatini', 'code' => 'sz'],
            ['name' => 'Madagascar', 'code' => 'mg'],
            ['name' => 'Mauritius', 'code' => 'mu'],
            ['name' => 'Seychelles', 'code' => 'sc'],
            ['name' => 'Comoros', 'code' => 'km'],
            ['name' => 'Djibouti', 'code' => 'dj'],
            ['name' => 'Somalia', 'code' => 'so'],
            ['name' => 'Eritrea', 'code' => 'er'],

            // Oceania
            ['name' => 'Australia', 'code' => 'au'],
            ['name' => 'New Zealand', 'code' => 'nz'],
            ['name' => 'Papua New Guinea', 'code' => 'pg'],
            ['name' => 'Fiji', 'code' => 'fj'],
            ['name' => 'Solomon Islands', 'code' => 'sb'],
            ['name' => 'Vanuatu', 'code' => 'vu'],
            ['name' => 'New Caledonia', 'code' => 'nc'],
            ['name' => 'French Polynesia', 'code' => 'pf'],
            ['name' => 'Samoa', 'code' => 'ws'],
            ['name' => 'American Samoa', 'code' => 'as'],
            ['name' => 'Tonga', 'code' => 'to'],
            ['name' => 'Tuvalu', 'code' => 'tv'],
            ['name' => 'Kiribati', 'code' => 'ki'],
            ['name' => 'Nauru', 'code' => 'nr'],
            ['name' => 'Palau', 'code' => 'pw'],
            ['name' => 'Marshall Islands', 'code' => 'mh'],
            ['name' => 'Micronesia', 'code' => 'fm'],
            ['name' => 'Northern Mariana Islands', 'code' => 'mp'],
            ['name' => 'Guam', 'code' => 'gu'],
            ['name' => 'Cook Islands', 'code' => 'ck'],
            ['name' => 'Niue', 'code' => 'nu'],
            ['name' => 'Tokelau', 'code' => 'tk'],
            ['name' => 'Pitcairn Islands', 'code' => 'pn'],
            ['name' => 'Wallis and Futuna', 'code' => 'wf'],
        ];

        foreach ($countries as $country) {
            \App\Models\Country::create($country);
        }

        $this->command->info('Countries created successfully!');
    }
}
